### PR TITLE
fix the updatifier issue

### LINKED ISSUE #52: Updatifier compatibility broken
The build.gradle file has some code in it that prevents EssentialCmds from working with Updatifier.

[View file here](https://github.com/hsyyid/EssentialCmds/blob/master/build.gradle#L93)

`project.version + getGitHash()` does not equal the exact tag that is found on GitHub. You should change it to `project.version`. It is preventing Updatifier from getting the tag from GitHub.

### PR DESCRIPTION
**Pull request by kinggoesgaming**
fix the updatifier issue

Now there are two fields in PluginInfo class, one for @Updatifier and one for @Plugin annotations.

Closes #52

### CODE REVIEW

**Comment by kinggoesgaming** [comment]
@hsyyid tell me if thats fine

**Comment by liach** [comment]
@kinggoesgaming Nope, Updatifier checks github release tag instead of commit hash.

**Comment by kinggoesgaming** [comment]
@liach the final result ends up with checking from the releases as visible from the compiled class 
deepinscreenshot20160207172304

The INFORMATIVE_VERSION is for @Plugin and VERSION is for @Updatifier.

**Comment by liach** [comment]
My bad, that's right.

**Comment by kinggoesgaming** [comment]
its ok it happens :wink:

**Pull request merged**
